### ISSUE TITLE
Query fails due to temp/cache table existing

### ISSUE THREAD

**Issue by neurolabs** [spotify/scio#710] opened 2017-07-06 07:35 UTC
Hi,

when repeating queries against a table, when the cache table is older (cache invalid), scio tries to query using the same temp table (see BigQueryClient#newQueryJob). This temp table then gets passed to the query job using a write disposition of "WRITE_EMPTY". This can't work, can it?

It leads to the following error:

```
root[ERROR] java.lang.RuntimeException: Query job failed: id: project-7a883810-2a72-4335-a9a5-b31da4c113f9, error: {"message":"Already Exists: Table project:scio_bigquery_staging_eu.scio_query_20170706065353_2093405976","reason":"duplicate"}
root[ERROR]     at com.spotify.scio.bigquery.BigQueryClient$$anonfun$3.apply(BigQueryClient.scala:321)
root[ERROR]     at com.spotify.scio.bigquery.BigQueryClient$$anonfun$3.apply(BigQueryClient.scala:316)
root[ERROR]     at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:248)
root[ERROR]     at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
root[ERROR]     at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
root[ERROR]     at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:247)
root[ERROR]     at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
root[ERROR]     at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
root[ERROR]     at com.spotify.scio.bigquery.BigQueryClient.waitForJobs(BigQueryClient.scala:316)
root[ERROR]     at com.spotify.scio.bigquery.BigQueryClient$$anon$4.waitForResult(BigQueryClient.scala:505)
root[ERROR]     at com.spotify.scio.bigquery.BigQueryClient.getQueryRows(BigQueryClient.scala:188)
root[ERROR]     at com.spotify.scio.bigquery.BigQueryClient.getTypedRows(BigQueryClient.scala:388)
```

This can be solved in many ways like:

* new temp table for invalid caches
* using WRITE_TRUNCATE
* ...

I'm unsure. If you point me in the right direction, I'm willing to create a pull request.

**Comment by neurolabs** [comment] 2017-07-06 07:43
Another thing to note: The error is only seen when querying the result of the submitted job.

**Comment by nevillelyh** [comment] 2017-07-06 16:18
This seems a duplicate of #556?
Do you have a consistent way of reproducing it?

**Comment by neurolabs** [comment] 2017-07-06 17:44
Sure, I do. I am only using scio-bigquery:

1. Read from table, scio creates a cache table
2. write to table
3. Read from table, scio reckons the cache is invalid, tries to create a cache table with the name of the existing table.

It's pretty obvious in the code, see BigQueryClient#newQueryJob, the else part of condition `sourceTimes.forall(_ < time)`.

My workaround is to delete the cache tables in the dataset created by scio programmatically (only possible via google lib).

**Closed** 2017-07-07 00:08 UTC
Labels: bug
