### ISSUE TITLE
Too many file descriptors potentially messing up sbt console

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#1124] opened 2018-04-23 14:04 UTC
Sometimes after running tests, the sbt console stop echoing back user input even though it's still running. We suspect `junit-interface` caused this and it might be fixable with some settings tweak.

**Comment by jto** [comment] 2018-04-23 14:06
I'll have a look at this. I can reproduce it every time on my laptop.

**Comment by jto** [comment] 2018-04-25 09:14
Seems to be caused by https://github.com/sbt/sbt/issues/937

**Comment by jto** [comment] 2018-04-27 12:45
I tried to workaround the problem using `Tags.limit(Tags.Test, 2)`. Any value above 1 and the test hangs on my machine...

**Comment by jto** [comment] 2020-02-26 14:13
Does not seem to happen anymore. Closing.

**Closed by jto** 2020-02-26 14:13 UTC
Labels: P2, help wanted
