### ISSUE TITLE
Make sure protobuf files writeen with Scio v0.6 can be read by 0.7

### ISSUE THREAD

**Issue by jto** [spotify/scio#1561] opened 2018-12-03 09:12 UTC
Scio 0.6 gets a protobuf coder using [`val elemCoder = this.getCoder[T]`](https://github.com/spotify/scio/blob/v0.6.1/scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala#L927) which should return an instance of [`ProtobufSerializer` from Chill](https://github.com/spotify/scio/blob/v0.6.1/scio-core/src/main/scala/com/spotify/scio/coders/KryoAtomicCoder.scala#L106).

`ProtobufSerializer` writes an `Int` and then writes the actual protobuf object [(code)](https://github.com/twitter/chill/blob/develop/chill-protobuf/src/main/java/com/twitter/chill/protobuf/ProtobufSerializer.java#L64-L65).

This ticket goal is to adress 2 issues: 

1. We need to make sure that files written by `saveAsProtobufFile` in Scio 0.6 can be read by Scio 0.7 (which uses [`ProtoCoder`](https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/coders/instances/ProtobufCoders.scala#L35)).
1. `ProtobufIO` is [pulling the protobuf `Coder` from the implicit context](https://github.com/spotify/scio/blob/master/scio-avro/src/main/scala/com/spotify/scio/avro/AvroIO.scala#L91) which looks like a terrible idea to me. I think we should hardcode `ProtoCoder` instead (or at least have it as a non-implicit parameter with `ProtoCoder` as default)

wdyt about the last point @regadas @ClaireMcGinty ?

**Comment by regadas** [comment] 2018-12-03 15:21
@jto double checked the implementation of `ProtobufSerializer` and `ProtoCoder` and they are on par. `ProtoCoder` uses the underlying `encode` method from `AbstractMessageLite` which does the same thing. Given this 1) should™ be ok. Nevertheless, I think we should check that `Coder.kryo` and `Coder.beam(ProtoCoder)` can be used interchangeably.

Regarding the 2) I guess you are worried about user custom definition of a `Coder[T]` that get's resolved instead of the `ProtobufCoders.protoMessageCoder`, leading to an expected behavior. I agree, this can be problematic.Also, since we will write a `protobuf` should we even allow override?

**Closed** 2018-12-03 18:14 UTC
Labels: P0
