### ISSUE TITLE
None.get errors when aggregating in a window

### ISSUE THREAD

**Issue by grindlemire** [spotify/scio#1620] opened 2019-01-21 17:39 UTC
Hi!

I have been running into issues in a streaming pipeline while draining on the dataflow runner. This is the exception I have been receiving: 
```
java.util.NoSuchElementException: None.get
at scala.None$.get(Option.scala:347)
at scala.None$.get(Option.scala:345)
at com.spotify.scio.util.Functions$$anon$5.extractOutput(Functions.scala:134)
at com.spotify.scio.util.Functions$$anon$5.extractOutput(Functions.scala:96)
at org.apache.beam.runners.dataflow.worker.WindmillStateInternals$WindmillCombiningState.read(WindmillStateInternals.java:920)
at org.apache.beam.runners.core.SystemReduceFn.onTrigger(SystemReduceFn.java:125)
at org.apache.beam.runners.core.ReduceFnRunner.onTrigger(ReduceFnRunner.java:1060)
at org.apache.beam.runners.core.ReduceFnRunner.onTimers(ReduceFnRunner.java:768)
at org.apache.beam.runners.dataflow.worker.StreamingGroupAlsoByWindowViaWindowSetFn.processElement(StreamingGroupAlsoByWindowViaWindowSetFn.java:95)
at org.apache.beam.runners.dataflow.worker.StreamingGroupAlsoByWindowViaWindowSetFn.processElement(StreamingGroupAlsoByWindowViaWindowSetFn.java:42)
at org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.invokeProcessElement(GroupAlsoByWindowFnRunner.java:115)
at org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.processElement(GroupAlsoByWindowFnRunner.java:73)
at org.apache.beam.runners.core.LateDataDroppingDoFnRunner.processElement(LateDataDroppingDoFnRunner.java:80)
at org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowsParDoFn.processElement(GroupAlsoByWindowsParDoFn.java:135)
at org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:45)
at org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:50)
at org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:202)
at org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:160)
at org.apache.beam.runners.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:77)
at org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker.process(StreamingDataflowWorker.java:1226)
at org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker.access$1000(StreamingDataflowWorker.java:141)
at org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker$6.run(StreamingDataflowWorker.java:965)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
```
This exception occurs when I try to drain a streaming pipeline containing a combineByKey on some tuples. My pipeline looks something like this:

```scala
sc.customInput("Input", pubsubIn(args("inputSub")))
      .map(unmarshalJson)
      .filter{!_.isEmpty}
      .withFixedWindows(
        duration = Duration.standardSeconds(windowSizeSeconds),
        options = WindowOptions(
          trigger = AfterWatermark.pastEndOfWindow()
          .withEarlyFirings(AfterProcessingTime.pastFirstElementInPane()
              .plusDelayOf(Duration.standardSeconds(earlyFiringSeconds)))
            .withLateFirings(AfterProcessingTime.pastFirstElementInPane()
              .plusDelayOf(Duration.standardSeconds(lateFiringSeconds))),
          accumulationMode = ACCUMULATING_FIRED_PANES,
          allowedLateness = Duration.standardDays(allowedLatenessDays)
        )
      )
      .distinctBy[String](f = getId)
      .filter{_!=null} // I also have noticed quite a few nulls when draining the pipeline
      .flatMap{m: Map[String, Any]=> 
         val k = (m.get("user").get.asInstanceOf[String], m.get("customer").get.asInstanceOf[String])
         val v = (m.getOrElse("label1", ""), m.getOrElse("label2", ""))
         Some((k, v)).toTraversable
      // This combines labels from the same key and customer into a set. So all the different 
      // label1s for a user are aggregated to a set of unique values and all the label2s for a user
      // are also aggregated into a set
      .combineByKey((v: (Any, Any))=>(Set(v._1), Set(v._2)))((s: (Set[Any], Set[Any]),v: (Any, Any))=>(s._1+v._1, s._2+v._2))((sa: (Set[Any], Set[Any]),sb: (Set[Any], Set[Any]))=>(sa._1++sb._1, sa._2++sb._2))
      // I have been using this map as a way of checking the integrity of the post aggregated values.
      // I have noticed that if I remove this map step I don't see issues but I don't see how this 
      // could cause the exception thrown.
      .map{kv: ((Any, Any), (Set[Any], Set[Any]))=>
        kv match {
          case null => {
            logger.info(s"kv was null or none! $kv")
          }
          case _ => {
            val k = kv._1
            val v = kv._2
            (k, v) match {
              case (null, _) | (_, null) => {
                logger.warn(s"k or v was null or none! ($k, $v)")
              }
              case _ => {
                kv
              }
            }
          }
        }
      .map{m=>
          mapper.writeValueAsString(m)
      }
      .saveAsPubsub(args("outputTopic"))
```
I am windowing into 60 second windows with 30 second early and late firings and an allowed lateness of 3 days. All the test data I am sending through is not delayed.

I have been reading through the scio code and attempting to reproduce with as simple a pipeline as possible. Although I could very well be mistaken I believe there may be an issue in the [mergeAccumulators](https://github.com/spotify/scio/blob/v0.7.0-beta1/scio-core/src/main/scala/com/spotify/scio/util/Functions.scala#L136) function. As far as I understand it, mergeAccumulators will return a tuple of `None` and an empty arrayList when `flattened` is empty. However if the last accumulator after all the accumulators have been merged is also empty, then a call to `extractOutput` would result in the exception I am receiving. It appears that when I drain my pipeline I am getting a lot of empty accumulators or none at all.

Instead of returning `None` for the value of `combined`, wouldn't we want to return an empty instance of the accumulator the user specifies (in my case it would be a `(Set[Any], Set[Any])`)? I could be misunderstanding the code as I am new to both scio and Beam but this is what seems to be causing this issue to me.

### Version
Scio: `0.7.0-beta1 `
Beam: `2.8.0`

**Comment by andrisnoko** [comment] 2019-01-28 21:45
@grindlemire we could not repro the issue. Could you provide another example and sample data?

```scala
sc.customInput("Read From Pubsub", org.apache.beam.sdk.io.gcp.pubsub.PubsubIO
      .readMessages()
      .fromSubscription("test"))
      .map { e => {
         val someValue = (e.getPayload.map(_.toChar)).mkString
        val stringToString: Map[String, Any] = Map("user" -> someValue, "customer" -> "test", "label1" ->
          "test", "label2" -> "test")
        stringToString
      }
      }
      .withFixedWindows(
        duration = Duration.standardSeconds(windowSizeSeconds),
        options = WindowOptions(
          trigger = AfterWatermark.pastEndOfWindow()
            .withEarlyFirings(AfterProcessingTime.pastFirstElementInPane()
              .plusDelayOf(Duration.standardSeconds(earlyFiringSeconds)))
            .withLateFirings(AfterProcessingTime.pastFirstElementInPane()
              .plusDelayOf(Duration.standardSeconds(lateFiringSeconds))),
          accumulationMode = AccumulationMode.ACCUMULATING_FIRED_PANES,
          allowedLateness = Duration.standardDays(allowedLatenessDays)
        )
      )
      .distinctBy[String](e => e("user").toString)
      /* .filter {
         _ != null
       } */// I also have noticed quite a few nulls when draining the pipeline
      .flatMap { m: Map[String, Any] =>
      val k = (m("user").toString, m("customer").toString)
      val v = (m.getOrElse("label1", ""), m.getOrElse("label2", ""))
      Some((k, v)).toTraversable
     }
      .combineByKey((v: (Any, Any)) => (Set(v._1), Set(v._2)))((s: (Set[Any], Set[Any]), v:
     (Any, Any)) => (s._1 + v._1, s._2 + v._2))((sa: (Set[Any], Set[Any]), sb: (Set[Any], Set[Any])) => (sa._1 ++ sb._1, sa._2 ++ sb._2))
      /*.map { kv: ((Any, Any), (Set[Any], Set[Any])) =>
        kv match {
          case null => {
            logger.info(s"kv was null or none! $kv")
          }
          case _ => {
            val k = kv._1
            val v = kv._2
            (k, v) match {
              case (null, _) | (_, null) => {
                logger.warn(s"k or v was null or none! ($k, $v)")
              }
              case _ => {
                kv
              }
            }
          }
        }
      }*/
      .map { m =>
        m.toString()
        println(m.toString())
      }
    sc.close()
```

**Comment by regadas** [comment] 2019-02-19 16:33
@grindlemire Can you try updating to a later version i.e: `0.7.1` and see if you still have issues?

**Comment by 4ndygu** [comment] 2019-04-17 15:10
Hi! Extending the issue -- I receive the following exception from my streaming pipeline on the dataflow runner

```
java.util.NoSuchElementException: None.get
        scala.None$.get(Option.scala:349)
        scala.None$.get(Option.scala:347)
        com.spotify.scio.util.Functions$ReduceFn.extractOutput(Functions.scala:196)
        com.spotify.scio.util.Functions$ReduceFn.extractOutput(Functions.scala:181)
        org.apache.beam.runners.dataflow.worker.WindmillStateInternals$WindmillCombiningState.read(WindmillStateInternals.java:919)
        org.apache.beam.runners.core.SystemReduceFn.onTrigger(SystemReduceFn.java:125)
        org.apache.beam.runners.core.ReduceFnRunner.onTrigger(ReduceFnRunner.java:1060)
        org.apache.beam.runners.core.ReduceFnRunner.onTimers(ReduceFnRunner.java:768)
        org.apache.beam.runners.dataflow.worker.StreamingGroupAlsoByWindowViaWindowSetFn.processElement(StreamingGroupAlsoByWindowViaWindowSetFn.java:95)
        org.apache.beam.runners.dataflow.worker.StreamingGroupAlsoByWindowViaWindowSetFn.processElement(StreamingGroupAlsoByWindowViaWindowSetFn.java:42)
        org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.invokeProcessElement(GroupAlsoByWindowFnRunner.java:115)
        org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.processElement(GroupAlsoByWindowFnRunner.java:73)
        org.apache.beam.runners.core.LateDataDroppingDoFnRunner.processElement(LateDataDroppingDoFnRunner.java:80)
        org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowsParDoFn.processElement(GroupAlsoByWindowsParDoFn.java:134)
        org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44)
        org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49)
        org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:201)
        org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:159)
        org.apache.beam.runners.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:76)
        org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker.process(StreamingDataflowWorker.java:1228)
        org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker.access$1000(StreamingDataflowWorker.java:143)
        org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker$6.run(StreamingDataflowWorker.java:967)
        java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        java.lang.Thread.run(Thread.java:745)
```

This exception occurs intermittently when I run a streaming pipeline containing a reduceByKey over a window. The pipeline looks like this: 

```
    val loginInputMapped = SCollection.unionAll(inputs)
      .withFixedWindows(Duration.standardHours(2))
      .map( data => {
        val iso_code = dcCountryGeoIPResolver().apply(data._2)
        val (city, lat, long) = dcCityGeoIPResolver().apply(data._2)
        val zero = 0
        // (username, (lat, long, ip, timestamp, platform , placeholder for reduce sum) )
        ( data._1, ( lat, long, data._2, data._3, data._4, zero.toFloat) )
      })
      .reduceByKey((blob1, blob2) => {
        // value should be (lat, lng, ips, times, platforms, pythagorean sum)
        (blob2._1, blob2._2, blob1._3 + "," + blob2._3, blob1._4 + "," + blob2._4,
          blob1._5 + "," + blob2._5, blob1._6 + blob2._6 + calculatePythagorean(blob1._1.toFloat,
          blob1._2.toFloat,
          blob2._1.toFloat,
          blob2._2.toFloat))
      })
      .map(data => TableRow(
        "username" -> data._1.toString,
        "ips" -> data._2._3,
        "timestamps" -> data._2._4,
        "platforms" -> data._2._5,
        "distance" -> data._2._6
      ))
      .saveAsBigQuery("output.output.output", schema, WRITE_APPEND, CREATE_IF_NEEDED)
```

**Comment by nevillelyh** [comment] 2019-04-18 17:17
Duplicate of #778 & #1159. We're adding some warning to `combine/sum` usage.

**Closed** 2019-04-19 15:05 UTC
Labels: P2, bug
