### ISSUE TITLE
side input list are partially or entirely Null non-deterministically since upgrade to scio 0.5.2

### ISSUE THREAD

**Issue by manuka2** [spotify/scio#1152] opened 2018-05-08 23:08 UTC
We recently upgraded scio version from 0.4.1 to 0.5.2 and one of our pipelines started to throw null pointer errors which ultimately lead to IO exception which causes job runs to fail.  I reverted the scio version back to 0.4.1 and ran the job with the same code, job finished without errors.

In one of the failed job runs, I logged more info about the behavior of the side input list and found out that some of the side input lists have null as elements (they're not supposed to: I redirected the data for side input list to text files and none of them are null) while the rest don't. This bug happens randomly at a very low rate (roughly estimated to be <= 10 every million) but it's harmful enough to cause the job to fail 9 out of 10 times. 

The side input list is supposed to be composed of 9999 strings:
A snippet of the customized error info:

E  45 elements are null  
E  9999 elements are null  
E  9999 elements are null  
E  9999 elements are null  
E  9999 elements are null  
E  9999 elements are null  
E  9999 elements are null  
E  9999 elements are null  
E  9999 elements are null  
E  9999 elements are null  
...

And the IO Exception errors:

```
 2018-05-07 (04:36:48) java.io.IOException: java.net.SocketException: Unexpected end of file from server
java.io.IOException: java.net.SocketException: Unexpected end of file from server
	at com.google.cloud.hadoop.util.AbstractGoogleAsyncWriteChannel.waitForCompletionAndThrowIfUploadFailed(AbstractGoogleAsyncWriteChannel.java:431)
	at com.google.cloud.hadoop.util.AbstractGoogleAsyncWriteChannel.close(AbstractGoogleAsyncWriteChannel.java:289)
	at java.nio.channels.Channels$1.close(Channels.java:178)
	at com.google.cloud.dataflow.worker.repackaged.com.google.common.io.CountingOutputStream.close(CountingOutputStream.java:68)
	at com.google.cloud.dataflow.worker.IsmSink$IsmSinkWriter.close(IsmSink.java:296)
	at com.google.cloud.dataflow.worker.util.common.worker.WriteOperation.finish(WriteOperation.java:95)
	at com.google.cloud.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:83)
	at com.google.cloud.dataflow.worker.BatchDataflowWorker.executeWork(BatchDataflowWorker.java:383)
	at com.google.cloud.dataflow.worker.BatchDataflowWorker.doWork(BatchDataflowWorker.java:355)
	at com.google.cloud.dataflow.worker.BatchDataflowWorker.getAndPerformWork(BatchDataflowWorker.java:286)
	at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.doWork(DataflowBatchWorkerHarness.java:134)
	at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:114)
	at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:101)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:37)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:94)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
	at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequestWithoutGZip(MediaHttpUploader.java:545)
	at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequest(MediaHttpUploader.java:562)
	at com.google.api.client.googleapis.media.MediaHttpUploader.resumableUpload(MediaHttpUploader.java:419)
	at com.google.api.client.googleapis.media.MediaHttpUploader.upload(MediaHttpUploader.java:336)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:427)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at com.google.cloud.hadoop.util.AbstractGoogleAsyncWriteChannel$UploadOperation.call(AbstractGoogleAsyncWriteChannel.java:357)
	... 4 more
```

**Comment by andrewsmartin** [comment] 2018-05-25 16:40
With this particular job the `SideInput` was small enough that it could be instead a singleton side input of `List[T]`. In this case the job ran without problems. I'm curious if this is an issue with `ListSideInput` on google's side.

**Comment by nevillelyh** [comment] 2018-06-06 12:42
Tried several runs with different combos of `main`/`side` size but couldn't repro.

```scala
import java.util.UUID

import com.spotify.scio._
import org.apache.beam.sdk.io.GenerateSequence

object Debug {
  def main(cmdlineArgs: Array[String]): Unit = {
    val (sc, args) = ContextAndArgs(cmdlineArgs)

    val main = sc.customInput("main", GenerateSequence.from(0).to(1000))
      .map(_ => UUID.randomUUID().toString)
    val side = sc.customInput("side", GenerateSequence.from(0).to(1000))
      .map(_ => UUID.randomUUID().toString)

    main.cross(side).count.materialize
    sc.close()
  }
}
```

**Comment by jbx** [comment] 2018-07-17 18:57
Could be related to #1190 or #1231 - we'll check

**Comment by nevillelyh** [comment] 2018-08-15 13:18
Closing for now since no one was able to reproduce for 3 months.

**Closed** 2018-11-29 22:54 UTC
Labels: P1, bug, wontfix
