### ISSUE TITLE
PubsubIO batch size should be configurable

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#936] opened 2017-11-21 22:43 UTC
This might hit service payload size limit. We should fix it upstream and maybe expose the setting.

https://github.com/apache/beam/blob/release-2.1.0/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIO.java

**Comment by nevillelyh** [comment] 2017-11-21 23:40
https://issues.apache.org/jira/browse/BEAM-3234

**Comment by ThatRfernand** [comment] 2018-08-08 19:04
https://issues.apache.org/jira/browse/BEAM-3234 is a duplicate of another issue, a PR for which addresses this concern.

**Comment by nevillelyh** [comment] 2018-08-08 20:32
The new upstream issue is https://issues.apache.org/jira/browse/BEAM-2660

**Comment by nevillelyh** [comment] 2018-08-08 20:36
https://issues.apache.org/jira/browse/BEAM-3218
https://github.com/apache/beam/pull/4275
https://github.com/spotify/scio/pull/1207

All address the same problem with a different approach - by checking against the max publish byte size.

**Comment by nevillelyh** [comment] 2018-08-10 14:33
Don't think the upstream PRs will get merged and released in time for 0.5.7 though. Move to 0.6.0 instead?

**Comment by nevillelyh** [comment] 2018-08-16 15:02
Upstream https://github.com/apache/beam/pull/3619 was recently merged and should be available in the next Beam release.

**Comment by nevillelyh** [comment] 2018-08-20 20:26
From the mailing list:
> Our release calendar indicates that the process for the 2.7.0 Beam release should start on September 7.

Which means that we won't have the upstream fix until then. Moving this to 0.7.0

**Closed** 2018-10-09 14:42 UTC
Labels: P2, backport, bug, good first issue
