### ISSUE TITLE
FlinkRunner Job graph is too complex to understand..

### ISSUE THREAD

**Issue by RohitR1** [spotify/scio#2893] opened 2020-04-18 19:49 UTC
Code is simple:

```bash
    sc.textFile(input)
      .map(_.trim)
      .flatMap(_.split("[^a-zA-Z']+").filter(_.nonEmpty))
      .countByValue
      .map(t => t._1 + ": " + t._2)
      .saveAsTextFile(output)
```

But Job graph is too complex to understand for some users who will just be monitoring graph:

<img width="1535" alt="ScioComplexGraph" src="https://user-images.githubusercontent.com/60442898/79669781-aee0a400-81db-11ea-9ef9-e1a6f26f4715.png">

**Comment by jto** [comment] 2020-06-09 09:39
Not sure we can do anything about this in Scio. Likely caused by the Beam runner.

**Comment by jto** [comment] 2020-06-25 08:42
Closing this issue. Flink does not let you control how the graph is rendered and may even "merge" transforms together if they are pipelined. There's nothing we can do about it.

**Closed by jto** 2020-06-25 08:42 UTC
Labels: enhancement, flink, wontfix
