### ISSUE TITLE
brew install scio error

### ISSUE THREAD

**Issue by honeyAndSw** [spotify/scio#1253] opened 2018-07-18 12:07 UTC
Hi there,
I'm trying to install scio REPL via `brew install scio` and it returns install error.
Using downloaded jar manually works though.

```
==> Installing scio from spotify/public
==> Downloading https://github.com/spotify/scio/releases/download/v0.5.5/scio-re
Already downloaded: (some location here)/Library/Caches/Homebrew/scio-0.5.5.jar
Error: invalid byte sequence in UTF-8
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:118:in `split'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:118:in `can_extract?'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:40:in `block in detect'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:39:in `each'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:39:in `detect'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:39:in `detect'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:50:in `stage'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:171:in `stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:189:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `run'
/usr/local/Homebrew/Library/Homebrew/resource.rb:188:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:115:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:93:in `stage'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/forwardable.rb:202:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2010:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1112:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:113:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:557:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:110:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:191:in `<main>'
```

**Comment by nevillelyh** [comment] 2018-07-18 12:46
Works fine in my environment. Seems like a common brew/ruby issue.
https://github.com/Homebrew/legacy-homebrew/issues/41640

**Comment by nevillelyh** [comment] 2018-07-20 03:11
I'm seeing this also after releasing scio 0.5.6. Need to look into it.

**Comment by honeyAndSw** [comment] 2018-07-20 07:33
@nevillelyh Thanks!

**Comment by nevillelyh** [comment] 2018-07-20 12:52
I can reproduce with the following snippet:

```ruby
require 'open3'

path = "/Users/neville/Library/Caches/Homebrew/scio-0.5.6.jar"
out, _, _ = Open3.capture3("zipinfo", "-1", path)
File.open("out", 'w') { |file| file.write(out) }
out.split("\n")
```

**Comment by nevillelyh** [comment] 2018-07-20 13:17
Turns out spire includes some unicode class names that end up being UTF-16 encoded in the jar info.

```
spire/optional/unicode/package$$anonfun$+á$1.class
spire/optional/unicode/package$$anonfun$+á$2.class
spire/optional/unicode/package$$anonfun$+á$3.class
spire/optional/unicode/package$$anonfun$+ú$1.class
spire/optional/unicode/package$$anonfun$+ú$2.class
spire/optional/unicode/package$$anonfun$+ú$3.class
```
This might need to be fixed in homebrew though.

**Comment by nevillelyh** [comment] 2018-07-20 13:59
Reported to brew: https://github.com/Homebrew/brew/issues/4522

**Comment by regadas** [comment] 2018-07-23 15:23
this is being fixed in https://github.com/Homebrew/brew/pull/4523

**Comment by nevillelyh** [comment] 2018-07-24 15:39
Verified that it works now after `brew update`.

**Closed by nevillelyh** 2018-07-24 15:39 UTC
Labels: bug
