### ISSUE TITLE
Negated matchers fail with BeamSQLRow

### ISSUE THREAD

**Issue by anish749** [spotify/scio#2487] opened 2019-12-03 22:17 UTC
The following test case for `BeamSQLTest` fails:

```
  it should "support queries on case classes with not matcher" in runWithContext { sc =>
    val schemaRes = BSchema.builder().addStringField("email").build()
    val expected = users.map { u =>
      Row.withSchema(schemaRes).addValue(u.email).build()
    }
    implicit def coderRowRes: Coder[Row] = Coder.row(schemaRes)
    val in = sc.parallelize(users)
    val r = in.query("select username from SCOLLECTION") // select username, but expected is email
    r shouldNot containInAnyOrder(expected)
  }

```

Test failure stack trace:
```
[info] - should support queries on case classes with not matcher *** FAILED *** (815 milliseconds)
[info]   com.esotericsoftware.kryo.KryoException: java.lang.NullPointerException
[info] Serialization trace:
[info] fieldIndices (org.apache.beam.sdk.schemas.Schema)
[info] schema (org.apache.beam.sdk.values.RowWithStorage)
[info] v$1 (com.spotify.scio.testing.SCollectionMatchers$$anon$3$$anon$4$$anonfun$3)
[info]   at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144)
[info]   at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543)
[info]   at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
[info]   at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
[info]   at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543)
[info]   at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
[info]   at com.twitter.chill.TraversableSerializer.read(Traversable.scala:43)
[info]   at com.twitter.chill.TraversableSerializer.read(Traversable.scala:21)
[info]   at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
[info]   at com.twitter.chill.SomeSerializer.read(SomeSerializer.scala:24)
[info]   ...
[info]   Cause: java.lang.NullPointerException:
[info]   at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.HashBiMap.seekByKey(HashBiMap.java:221)
[info]   at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.HashBiMap.put(HashBiMap.java:267)
[info]   at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.HashBiMap.put(HashBiMap.java:260)
[info]   at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:162)
[info]   at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:39)
[info]   at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
[info]   at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
[info]   at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543)
[info]   at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
[info]   at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
[info]   ...
```

**Comment by jto** [comment] 2020-01-10 15:48
What would be the expected behaviour here ? 

The query fails because "username" is not a thing in the schema / row. To me that seems to be the expected behaviour. The query is wrong so it just crashes.

**Comment by jto** [comment] 2020-01-23 13:29
`containInAnyOrder` expects you to pass a `Coder[T]`.  It will use that coder on `r`.

The schema you pass has an `email` field but the rows you get from running the query do not, so you are just passing a broken `Coder`. 

I don't think there's anything wrong with `containInAnyOrder`. Closing the issue.
The error message could be more explicit though.

**Closed by jto** 2020-01-23 13:29 UTC
Labels: bug
