### ISSUE TITLE
AggregateByKey does not return complete protobuf message

### ISSUE THREAD

**Issue by annaks** [spotify/scio#729] opened 2017-07-17 23:23 UTC
scio version = 0.2.12
scala version = 2.11.8

Recently, `aggregateByKey` does not return a complete protobuf message as it had previously when run with Dataflow.

Tests pass as expected and running locally also returns expected results but when using `BlockingDataflowPipelineRunner` and submitting the job to Dataflow, the data is missing the `id` fields.

For the following snippet when run on Dataflow, only the `ms_played` field is saved to file whereas I would expect the `id` field also to be set as it is set (as it copies an `Artist` message).  Previously to July 11th, the code would return an `Artist` message with all fields set (both `ms_played` and `id`) when run on Dataflow.

```
import com.spotify.creator.test.protobuf.Test.{Artist, ArtistUser}
import com.spotify.scio.ContextAndArgs

object TestAggregate {

  def combine(artistA: Artist, artistB: Artist): Artist = {
    val totalMsPlayed = artistA.getMsPlayed + artistB.getMsPlayed
    Artist
      .newBuilder(artistA)
      .clearMsPlayed()
      .setMsPlayed(totalMsPlayed)
      .build()
  }

  def transform(artist: Artist, artistUser: (ArtistUser, Artist)): Artist = {
    val totalMsPlayed = artist.getMsPlayed + artistUser._1.getMsPlayed
    Artist
      .newBuilder(artistUser._2)
      .clearMsPlayed()
      .setMsPlayed(totalMsPlayed)
      .build()
  }

  def aggregateStuff(a: SCollection[ArtistUser]): SCollection[Artist] = {
    a.keyBy(_.getId)
      .map{ case(k, v) =>
        (k, (v, Artist.newBuilder.setId(v.getId).setMsPlayed(v.getMsPlayed).build))
      }
      .aggregateByKey(Artist.newBuilder.build)(transform, combine)
      .values
  }

  def main(cmdlineArgs: Array[String]): Unit = {
    val (sc, args) = ContextAndArgs(cmdlineArgs)

    val a = sc.parallelize(Seq(ArtistUser.newBuilder.setId("a").setUserId("123").setMsPlayed(10L).build,
      ArtistUser.newBuilder.setId("a").setUserId("123").setMsPlayed(2L).build,
      ArtistUser.newBuilder.setId("a").setUserId("123").setMsPlayed(300L).build,
      ArtistUser.newBuilder.setId("b").setUserId("123").setMsPlayed(10L).build))

    aggregateStuff(a)
      .saveAsTextFile("testAggregateByKey")
    sc.close()
  }
}
```

which uses 2 protobuf messages as described here:

```
syntax = "proto2";

package protobuf.schemas;

option java_package = "com.spotify.creator.test.protobuf";
option optimize_for = SPEED;
option java_outer_classname = "Test";


// Next ID: 4
message ArtistUser {
    optional string id = 1;
    optional string user_id = 2;
    optional int64 ms_played = 3;
}

// Next ID: 3
message Artist {
    optional string id = 1;
    optional int64 ms_played = 2;
}
```

Output: 
```
ms_played: 312
ms_played: 10
```

Expected Output:
```
id: "a", ms_played: 312
id: "b", ms_played: 10
```

Here are some tests that show that each function `transform` and `combine` returns as expected.

```
class TestAggregateTest extends PipelineSpec {

  "aggregateStuff" should "produce Artist" in {
    runWithContext { sc =>
      val input = sc.parallelize(Seq(ArtistUser.newBuilder.setId("a").setUserId("123").setMsPlayed(10L).build,
        ArtistUser.newBuilder.setId("a").setUserId("123").setMsPlayed(2L).build,
        ArtistUser.newBuilder.setId("a").setUserId("123").setMsPlayed(300L).build,
        ArtistUser.newBuilder.setId("b").setUserId("123").setMsPlayed(10L).build))

      val output = Seq(
        Artist.newBuilder.setId("a").setMsPlayed(312L).build,
        Artist.newBuilder.setId("b").setMsPlayed(10L).build)

      TestAggregate.aggregateStuff(input) should containInAnyOrder(output)
    }
  }

  "transform" should "produce Artist" in {
    val inputA = Artist.newBuilder.setId("a").setMsPlayed(10L).build
    val inputB = ArtistUser.newBuilder.setId("a").setUserId("123").setMsPlayed(2L).build
    val inputC = Artist.newBuilder.setId(inputB.getId).setMsPlayed(inputB.getMsPlayed).build

    val output = Artist.newBuilder.setId("a").setMsPlayed(12L).build

    TestAggregate.transform(inputA, (inputB, inputC)) shouldEqual output
  }

  "combine" should "produce Artist" in {
    val inputA = Artist.newBuilder.setId("a").setMsPlayed(10L).build
    val inputB = Artist.newBuilder.setId("a").setMsPlayed(2L).build

    val output = Artist.newBuilder.setId("a").setMsPlayed(12L).build

    TestAggregate.combine(inputA, inputB) shouldEqual output
  }
  
}
```

Results when run with `DirectPipelineRunner`:
```
id: "b"
ms_played: 10

id: "a"
ms_played: 312
```

Results when run on Dataflow with `BlockingDataflowPipelineRunner`:
```
ms_played: 312

ms_played: 10
```

**Comment by nevillelyh** [comment] 2017-07-18 15:32
Conformed that I can repro in latest Beam branch as well.

**Comment by nevillelyh** [comment] 2017-07-18 15:45
Added some assertions and found that `artistA.getId` is empty in `def combine`.

**Comment by nevillelyh** [comment] 2017-07-18 19:42
I'm able to reproduce this with vanilla Beam in https://github.com/nevillelyh/beam-proto-dbg. Will report to Google.

**Comment by kennknowles** [comment] 2017-07-19 03:56
Hello from Beam-land!

I believe the problem is `aggregateByKey(Artist.newBuilder.build)`. In your translation to raw Beam Java this manifests as `createAccumulator() { return Artist.newBuilder().build(); }`. What is happening is that this accumulator is being created and all inputs added to it, so there's no id to propagate.

This has always been a possible way of invoking a `CombineFn` but some recent internal changes cause it to happen more frequently on Dataflow. You don't experience this on the DirectRunner because it does not exercise this path, but it will after apache/beam#3579 merges in. Incidentally, the DirectRunner also doesn't exercise `mergeAccumulators` until after that. We are toying with developing something like a `CombineFnTester` to help users exercise the many possible code paths here.

In terms of the Beam APIs, my recommendation would be to `.setId` in `extractOutput`. I think in Scio this means you need to use `aggregateByKey(Aggregator[V, A, U)` or map the output afterwards.

**Comment by nevillelyh** [comment] 2017-07-19 04:59
Thanks, great catch! Totally missed this.

So in this case `artistA` in `def combine` was not the result of `def transform`, but the original `Artist.newBuilder.build`. And `Artist.newBuilder(artistA)` in `combine` missed out the ID field.

The original code can be fixed by modifying `combine` to the following, in case either input is zero.

```scala
def combine(artistA: Artist, artistB: Artist): Artist = {
    val totalMsPlayed = artistA.getMsPlayed + artistB.getMsPlayed
    val id = if (artistA.getId.nonEmpty) artistA.getId else artistB.getId
    Artist
      .newBuilder()
      .setId(id)
      .setMsPlayed(totalMsPlayed)
      .build()
  }
```

I'd say `aggregateByKey` still behaves as expected though. It's just that `combOp` failed to satisfy the `0 + x = x` property.
`def aggregateByKey(zeroValue: U)(seqOp: (U, V) => U, combOp: (U, U) => U)`

**Closed** 2017-07-20 02:40 UTC
Labels: bug, invalid
