### ISSUE TITLE
Multiple Windowing AllowedTimestampSkew

### ISSUE THREAD

**Issue by Juta** [spotify/scio#1233] opened 2018-07-09 15:48 UTC
I am trying to apply two windows from a streaming pubsub source. The first one should group the messages in a session window of 30s while the second one should use a session window of 10s (both with the same session id). The result should be one object with a computed attribute for session 1 and session 2, so I am trying to apply 2 consecutive windows. It is important also to use the timestamp from the event rather then the processing time.

My problem is that the pipeline gives an IllegalArgumentException: Cannot output with timestamp 2018-07-09T14:51:59.697Z. Output timestamps must be no earlier than the timestamp of the current input (2018-07-09T14:52:29.696Z) minus the allowed skew. This happens where I change the timestamp a second time.

If I change the skew my pipeline waits until the skew period is passed (seems like it is stuck and doing nothing) and then still emits the error. If I remove the code to change the timestamp a second time, the pipeline runs but the window is not applied correctly.

I am unsure if this is a bug or if there is a mistake in my code/reasoning. Also I don't understand how the timestamp I want to apply could be earlier then the current timestamp of the message since I combine them with EARLIEST timestamp. Does anyone know what the problem is?

This is my code:
```
object TestWindowing {

  val formatter = DateTimeFormat.forPattern("yyyyMMddHHmmssSSS");

  @BigQueryType.toTable
  case class Message(key: String, text: String, time: Instant)

  def convertMessage(line: String): Message = {
    val json: JsValue = Json.parse(line)
    new Message((json \ "key").as[String],
              (json \ "text").as[String],
              Instant.parse((json \ "time").as[String], formatter))
  }
 
 def main(cmdlineArgs: Array[String]): Unit = {

    val (sc, args) = ContextAndArgs(cmdlineArgs)
    sc.optionsAs[StreamingOptions].setStreaming(true)

    val rawEvents = sc.withName("Read Pubsub").pubsubSubscription(args("subscription"))
      .withName("Transform to Message").map(convertMessage)
      .withName("Set timestamps").timestampBy(
        m => m.time, new Duration(120000)
      )
      .withName("Generate session key").map(m => (m.key, m))
      .withName("Group by window").withSessionWindows(Duration.standardSeconds(30L), options = WindowOptions(timestampCombiner = TimestampCombiner.EARLIEST))
      .withName("Group by key").groupByKey
      .withName("Indicate duplicate messages for 30s window").applyTransform(ParDo.of(
        new DoFn[(String, Iterable[Message]), Message]{
          @ProcessElement
          private [extra] def processElement(c: DoFn[(String, Iterable[Message),
                                              Message]#ProcessContext): Unit = {
            val element = c.element()
            element._2.foreach { m =>
              // ... (do some processing with m)
              c.output(m)
            }
          }
        }))
        
      .withName("Set timestamps").timestampBy(
        m => m.time, new Duration(120000)
      )
      .withName("Generate session key").map(m => (m.key, m))
      .withName("Group by window").withSessionWindows(Duration.standardSeconds(10L))
      .withName("Group by key").groupByKey
      .withName("Indicate duplicate messages for 10s window").applyTransform(ParDo.of(
        new DoFn[(String, Iterable[Message]), Message]{
          @ProcessElement
          private [extra] def processElement(c: DoFn[(String, Iterable[Message),
                                              Message]#ProcessContext): Unit = {
            val element = c.element()
            element._2.foreach { m =>
              // ... (do some processing with m)
              c.output(m)
            }
          }
        }))
      .withName("Write to BQ").saveAsTypedBigQuery(args("output"), WRITE_APPEND)

    val result = sc.close().waitUntilFinish()
  }
}
```

**Comment by jto** [comment] 2018-07-10 09:55
It's kinda hard to tell for sure but *I think* it might be caused by late data. 

Your `DoFn` will emit element with the timestamp set to the timestamp of the earliest element in the group. (because: `options = WindowOptions(timestampCombiner = TimestampCombiner.EARLIEST)`) and because you're using `c.output(m)` which "will have the same timestamp and be in the same windows as the input element passed to the method annotated with @ProcessElement."

Also according to https://beam.apache.org/documentation/sdks/javadoc/2.3.0/org/apache/beam/sdk/transforms/windowing/TimestampCombiner.html#LATEST
> If data arrives late, it has no effect on the output timestamp. 

So if an Message arrives late for some reason, your pipeline may try to set the timestamp too early.

I suggest you try to use `c. outputWithTimestamp` and set the timestamp directly.

**Comment by Juta** [comment] 2018-07-10 12:01
I tried using the outputWithTimestamp method when processing the messages in the first window but I get the same error. Is there any way to change the timestamp other than that after (or during) a group by window operation?

**Comment by jto** [comment] 2018-07-10 13:00
Could you reproduce the behaviour in a minimal test application with a test suite demonstrating the issue so that a can have a look at it ?

**Comment by jbx** [comment] 2019-01-18 15:45
Closing this since we could not repro and it may have been fixed in later beam versions.

**Closed by jbx** 2019-01-18 15:45 UTC
Labels: wontfix
