### ISSUE TITLE
SideInput not refreshing on Global Window

### ISSUE THREAD

**Issue by calonso** [spotify/scio#1190] opened 2018-05-30 15:39 UTC
I've created [this mini job](https://github.com/calonso/beam_experiments/blob/master/refreshingsideinput/src/main/scala/com/mrcalonso/RefreshingSideInput.scala) to reproduce it.

The steps to follow are:
  1. Create one single table on the target BQ
  1. Run the job and see the expected messages in the logs
  1. Create a new table on BQ and patch (update the existing one)
  1. Wait for the following schemas refresh and see
      1. `Retrieving schema for ...` both tables
      1. The main stream logs still showing `Current schemas side has 1 keys` instead of the expected 2

If running [with plain PCollectionViews instead](https://github.com/calonso/beam_experiments/blob/master/refreshingsideinput/src/main/scala/com/mrcalonso/RefreshingSideInput2.scala) it works as expected

**Comment by calonso** [comment] 2018-05-31 17:14
FYI: After updating the example and adding tests to it it feels there is slightly more, my conclusions below:
* DirectRunner doesn't update already existing keys on the multimap when using PCollectionView
* SideInput implementation never updates on the global window:
  * Does not add new keys
  * Does not add new values to existing keys

**Comment by jto** [comment] 2018-06-25 08:12
Is that really a bug in Scio ? AFAIK side inputs are immutable (at least per-time window), so unless you use either a time window or a trigger, there's no reason to think they'll be updating. 

The javadoc says that `PCollectionView` produces "a single value per window as input and produces a PCollectionView that returns the value in the main input window when read as a side input." (https://beam.apache.org/documentation/sdks/javadoc/2.4.0/org/apache/beam/sdk/transforms/View.AsSingleton.html)

Link the question you asked on beam's mailing list which essentially comes to the same conclusion: https://lists.apache.org/thread.html/ef97c2744edf11ec84be180a8076c2027eb2ef6427a1ef3895bc7a97@%3Cuser.beam.apache.org%3E

Thought @nevillelyh ?

**Comment by jto** [comment] 2018-06-27 09:12
Closing the issue as it does not seem to be a bug in Scio.

**Comment by calonso** [comment] 2018-06-28 15:23
Global window side inputs are not immutable I think, specifically, multimaps allow for multiple firings of the side input within the same window as [this other thread](https://lists.apache.org/thread.html/e9518f5d5f4bcf7bab02de2cb9fe1bd5293d87aa12d46de1eac4600b@%3Cuser.beam.apache.org%3E) seems to point.

I thought this was a bug in Scio after discovering that Scio's `SideInput` and Beam's `PCollectionView` behave differently with regards to updates and sharing those findings with @nevillelyh on Gitter. I wrote a couple of example jobs [here](https://github.com/calonso/beam_experiments/tree/master/refreshingsideinput)

**Comment by jto** [comment] 2018-07-05 14:13
Hey @calonso,
I'm trying to reproduce the issue and I can't get the `SideInput` to be refreshed even using `RefreshingSideInput2`.

I get the following AssertionError when running your test: 

```
[info] RefreshingSideInput2Test:
[info] RefreshingSideInput2
[info] - should refresh schemas *** FAILED ***
[info]   java.lang.AssertionError: apply@{Matchers.scala:6666}1/ParMultiDo(anon$7).output:
[info] Expected: iterable over [<KV{User, List({fields=[{mode=REQUIRED, name=user_id, type=STRING}]})}>, <KV{User, List({fields=[{mode=REQUIRED, name=user_id, type=STRING}]}, {fields=[{mode=REQUIRED, name=user_id, type=STRING}, {mode=REQUIRED, name=name, type=STRING}]})}>] in any order
[info]      but: Not matched: <KV{User, List({fields=[{mode=REQUIRED, name=user_id, type=STRING}]})}>
[info]   at org.apache.beam.sdk.testing.PAssert$PAssertionSite.capture(PAssert.java:167)
[info]   at org.apache.beam.sdk.testing.PAssert.that(PAssert.java:377)
[info]   at org.apache.beam.sdk.testing.PAssert.that(PAssert.java:369)
[info]   at com.spotify.scio.testing.SCollectionMatchers$$anon$1$$anon$11$$anonfun$apply$1.apply(SCollectionMatchers.scala:186)
[info]   at com.spotify.scio.testing.SCollectionMatchers$$anon$1$$anon$11$$anonfun$apply$1.apply(SCollectionMatchers.scala:185)
[info]   at com.spotify.scio.testing.SCollectionMatchers.com$spotify$scio$testing$SCollectionMatchers$$m(SCollectionMatchers.scala:84)
[info]   at com.spotify.scio.testing.SCollectionMatchers$$anon$1$$anon$11.apply(SCollectionMatchers.scala:188)
[info]   at com.spotify.scio.testing.SCollectionMatchers$$anon$1$$anon$11.apply(SCollectionMatchers.scala:174)
[info]   at com.spotify.scio.testing.SCollectionMatchers$IterableMatcher.apply(SCollectionMatchers.scala:57)
[info]   at com.spotify.scio.testing.SCollectionMatchers$IterableMatcher.apply$(SCollectionMatchers.scala:57)
[info]   at com.spotify.scio.testing.SCollectionMatchers$$anon$1.apply(SCollectionMatchers.scala:172)
[info]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6666)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
[info]   at com.mrcalonso.RefreshingSideInput2Test$.com$mrcalonso$RefreshingSideInput2Test$$assertSchemas(RefreshingSideInput2Test.scala:171)
[info]   at com.mrcalonso.RefreshingSideInput2Test.$anonfun$new$2(RefreshingSideInput2Test.scala:51)
[info]   at com.mrcalonso.RefreshingSideInput2Test.$anonfun$new$2$adapted(RefreshingSideInput2Test.scala:45)
[info]   at com.spotify.scio.testing.PipelineTestUtils.runWithContext(PipelineTestUtils.scala:40)
[info]   at com.spotify.scio.testing.PipelineTestUtils.runWithContext$(PipelineTestUtils.scala:38)
[info]   at com.mrcalonso.RefreshingSideInput2Test.runWithContext(RefreshingSideInput2Test.scala:15)
[info]   at com.mrcalonso.RefreshingSideInput2Test.$anonfun$new$1(RefreshingSideInput2Test.scala:45)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at com.mrcalonso.RefreshingSideInput2Test.com$spotify$scio$testing$RunEnforcementJobTest$$super$withFixture(RefreshingSideInput2Test.scala:15)
[info]   at com.spotify.scio.testing.RunEnforcementJobTest.withFixture(RunEnforcementJobTest.scala:61)
[info]   at com.spotify.scio.testing.RunEnforcementJobTest.withFixture$(RunEnforcementJobTest.scala:57)
[info]   at com.mrcalonso.RefreshingSideInput2Test.withFixture(RefreshingSideInput2Test.scala:15)
[info]   at org.scalatest.FlatSpecLike.invokeWithFixture$1(FlatSpecLike.scala:1680)
[info]   at org.scalatest.FlatSpecLike.$anonfun$runTest$1(FlatSpecLike.scala:1692)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.FlatSpecLike.runTest(FlatSpecLike.scala:1692)
[info]   at org.scalatest.FlatSpecLike.runTest$(FlatSpecLike.scala:1674)
[info]   at org.scalatest.FlatSpec.runTest(FlatSpec.scala:1685)
[info]   at org.scalatest.FlatSpecLike.$anonfun$runTests$1(FlatSpecLike.scala:1750)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
[info]   at scala.collection.immutable.List.foreach(List.scala:389)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
[info]   at scala.collection.immutable.List.foreach(List.scala:389)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info]   at org.scalatest.FlatSpecLike.runTests(FlatSpecLike.scala:1750)
[info]   at org.scalatest.FlatSpecLike.runTests$(FlatSpecLike.scala:1749)
[info]   at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1685)
[info]   at org.scalatest.Suite.run(Suite.scala:1147)
[info]   at org.scalatest.Suite.run$(Suite.scala:1129)
[info]   at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1685)
[info]   at org.scalatest.FlatSpecLike.$anonfun$run$1(FlatSpecLike.scala:1795)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info]   at org.scalatest.FlatSpecLike.run(FlatSpecLike.scala:1795)
[info]   at org.scalatest.FlatSpecLike.run$(FlatSpecLike.scala:1793)
[info]   at com.mrcalonso.RefreshingSideInput2Test.com$spotify$scio$testing$PipelineSpec$$super$run(RefreshingSideInput2Test.scala:15)
[info]   at com.spotify.scio.testing.PipelineSpec.run(PipelineSpec.scala:73)
[info]   at com.spotify.scio.testing.PipelineSpec.run$(PipelineSpec.scala:69)
[info]   at com.mrcalonso.RefreshingSideInput2Test.run(RefreshingSideInput2Test.scala:15)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:106)
[info]   at sbt.TestRunner.run(TestFramework.scala:117)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:262)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:233)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:262)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:262)
[info]   at sbt.TestFunction.apply(TestFramework.scala:271)
[info]   at sbt.Tests$.$anonfun$toTask$1(Tests.scala:281)
[info]   at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:66)
[info]   at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[info]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[info]   at sbt.Execute.work(Execute.scala:272)
[info]   at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[info]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   Cause: java.lang.AssertionError: Expected: iterable over [<KV{User, List({fields=[{mode=REQUIRED, name=user_id, type=STRING}]})}>, <KV{User, List({fields=[{mode=REQUIRED, name=user_id, type=STRING}]}, {fields=[{mode=REQUIRED, name=user_id, type=STRING}, {mode=REQUIRED, name=name, type=STRING}]})}>] in any order
[info]      but: Not matched: <KV{User, List({fields=[{mode=REQUIRED, name=user_id, type=STRING}]})}>
[info]   at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
[info]   at org.junit.Assert.assertThat(Assert.java:956)
[info]   at org.junit.Assert.assertThat(Assert.java:923)
[info]   at org.apache.beam.sdk.testing.PAssert$AssertContainsInAnyOrder.apply(PAssert.java:1321)
[info]   at org.apache.beam.sdk.testing.PAssert$AssertContainsInAnyOrder.apply(PAssert.java:1300)
[info]   at org.apache.beam.sdk.testing.PAssert$CheckRelationAgainstExpected.apply(PAssert.java:965)
[info]   at org.apache.beam.sdk.testing.PAssert$CheckRelationAgainstExpected.apply(PAssert.java:945)
[info]   at org.apache.beam.sdk.testing.PAssert.doChecks(PAssert.java:1249)
[info]   at org.apache.beam.sdk.testing.PAssert$GroupedValuesCheckerDoFn.processElement(PAssert.java:1214)
[info]   at org.apache.beam.sdk.testing.PAssert$GroupedValuesCheckerDoFn$DoFnInvoker.invokeProcessElement(Unknown Source)
[info]   at org.apache.beam.runners.direct.repackaged.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:177)
[info]   at org.apache.beam.runners.direct.repackaged.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:141)
[info]   at org.apache.beam.runners.direct.repackaged.runners.core.SimplePushbackSideInputDoFnRunner.processElementInReadyWindows(SimplePushbackSideInputDoFnRunner.java:72)
[info]   at org.apache.beam.runners.direct.ParDoEvaluator.processElement(ParDoEvaluator.java:179)
[info]   at org.apache.beam.runners.direct.DoFnLifecycleManagerRemovingTransformEvaluator.processElement(DoFnLifecycleManagerRemovingTransformEvaluator.java:51)
[info]   at org.apache.beam.runners.direct.DirectTransformExecutor.processElements(DirectTransformExecutor.java:161)
[info]   at org.apache.beam.runners.direct.DirectTransformExecutor.run(DirectTransformExecutor.java:125)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
```

It seems to me that your test shows that the SideInput is not refreshed even when using beam directly. Am I missing something ?

**Comment by jto** [comment] 2018-07-05 14:36
The schema in the test is UserSchemaV1, so it suggest that it did not refresh the side input. If I get the issue your linking correctly, we should see userSchemaV2.

**Comment by calonso** [comment] 2018-07-05 15:01
So there are two different tests. One that adds a new entry to the side input and another that refreshes  the already known entries by adding more 'versions' to the iterable of the multimap. The latter test fails on both environments (Scio and plain beam), but the former fails only using scio views... Does it make sense?

**Comment by jto** [comment] 2018-07-05 15:05
Aaaah right. I see it now. Sorry to be a be thick... 
Thanks for the explanation it's much clearer now 👍

**Comment by jto** [comment] 2018-07-06 09:36
Your test actually fails because the type of the iterable in `expected` does not match to the one used internally by Scio.  Scio's behaviour is in fact consistent with beam.

If you change your code to:

```scala
def iterable[A](a: A): Iterable[A] = {
  val l = new java.util.ArrayList[A]
  l.add(a)
  scala.collection.convert.Wrappers.JIterableWrapper(l)
}

val expected = Iterable(
  KV.of(UserType, iterable(toSchema(UserSchemaV1))),
  KV.of(UserType, iterable(toSchema(UserSchemaV1))),
  KV.of(ClientType, iterable(toSchema(clientSchema)))
)
```

The test passes

**Comment by jto** [comment] 2018-07-06 09:53
Reopening because the test is flaky. The internal scio cache on SideInput makes it undeterministic: https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/values/SideInput.scala#L36-L42

@nevillelyh What's the purpose of that cache ? Can we get rid of ot ?

**Comment by jto** [comment] 2018-07-06 13:56
@nevillelyh Seems to be trickier than that. 

It's actually a concurrency issue. Apparently the same instance of `SideInput` is used simultaneously in different threads making the cache set/get order non-deterministic. Hence, the flaky test. 

`SideInput` has to be serializable, so using a `ThreadLocal` is out of the equation.

**Comment by jto** [comment] 2018-07-09 09:21
I added the following logs:

```scala
trait SideInput[T] extends Serializable {
  private var cache: T = _
  @transient private var window: BoundedWindow = _

  private[values] def get[I, O](context: DoFn[I, O]#ProcessContext): T

  def getCache[I, O](context: DoFn[I, O]#ProcessContext, window: BoundedWindow): T = {
    println(s"""> getCache $cache,
      this.window: ${this.window}
      window: $window
    """)
    if (cache == null || this.window != window) {
      this.window = window
      cache = get(context)
      println(s"""> updating
        cache:  $cache
        window: $window
      """)
    } else {
      println(s">> Cache HIT")
    }
    val x = get(context)

    if(cache != x && cache != null) {
      println(s">>> Stale cache")
      println(s"correct value: ${x}")
      println(s"cached  value: ${cache}")
    }

    cache
  }

  private[values] val view: PCollectionView[_]
}
```

And the logs when tests are passing and tests are failing:


### TEST PASSING
---------------------------------------

```
> getCache null,
      this.window: null
      window: org.apache.beam.sdk.transforms.windowing.GlobalWindow@20d6bd24

> getCache null,
      this.window: null
      window: org.apache.beam.sdk.transforms.windowing.GlobalWindow@20d6bd24

> updating
        cache:  Map({datasetId=dummy-dset, projectId=dummy-proj, tableId=User} -> Wrappers.JIterableWrapper({fields=[{mode=REQUIRED, name=user_id, type=STRING}]}))
        window: org.apache.beam.sdk.transforms.windowing.GlobalWindow@20d6bd24

> updating
        cache:  Map({datasetId=dummy-dset, projectId=dummy-proj, tableId=User} -> Wrappers.JIterableWrapper({fields=[{mode=REQUIRED, name=user_id, type=STRING}]}))
        window: org.apache.beam.sdk.transforms.windowing.GlobalWindow@20d6bd24

> getCache Map({datasetId=dummy-dset, projectId=dummy-proj, tableId=User} -> Wrappers.JIterableWrapper({fields=[{mode=REQUIRED, name=user_id, type=STRING}]})),
      this.window: org.apache.beam.sdk.transforms.windowing.GlobalWindow@20d6bd24
      window: org.apache.beam.sdk.transforms.windowing.GlobalWindow@20d6bd24

>> Cache HIT

> getCache null,
      this.window: null
      window: org.apache.beam.sdk.transforms.windowing.GlobalWindow@20d6bd24

> updating
        cache:  Map({datasetId=dummy-dset, projectId=dummy-proj, tableId=Client} -> Wrappers.JIterableWrapper({fields=[{mode=REQUIRED, name=client_id, type=STRING}]}), {datasetId=dummy-dset, projectId=dummy-proj, tableId=User} -> Wrappers.JIterableWrapper({fields=[{mode=REQUIRED, name=user_id, type=STRING}]}))
        window: org.apache.beam.sdk.transforms.windowing.GlobalWindow@20d6bd24
```

### TEST FAILING
---------------------------------------

```
> getCache null,
      this.window: null
      window: org.apache.beam.sdk.transforms.windowing.GlobalWindow@497514c

> getCache null,
      this.window: null
      window: org.apache.beam.sdk.transforms.windowing.GlobalWindow@497514c

> updating
        cache:  Map({datasetId=dummy-dset, projectId=dummy-proj, tableId=User} -> Wrappers.JIterableWrapper({fields=[{mode=REQUIRED, name=user_id, type=STRING}]}))
        window: org.apache.beam.sdk.transforms.windowing.GlobalWindow@497514c

> updating
        cache:  Map({datasetId=dummy-dset, projectId=dummy-proj, tableId=User} -> Wrappers.JIterableWrapper({fields=[{mode=REQUIRED, name=user_id, type=STRING}]}))
        window: org.apache.beam.sdk.transforms.windowing.GlobalWindow@497514c

> getCache null,
      this.window: null
      window: org.apache.beam.sdk.transforms.windowing.GlobalWindow@497514c

> updating
        cache:  Map({datasetId=dummy-dset, projectId=dummy-proj, tableId=User} -> Wrappers.JIterableWrapper({fields=[{mode=REQUIRED, name=user_id, type=STRING}]}))
        window: org.apache.beam.sdk.transforms.windowing.GlobalWindow@497514c

> getCache Map({datasetId=dummy-dset, projectId=dummy-proj, tableId=User} -> Wrappers.JIterableWrapper({fields=[{mode=REQUIRED, name=user_id, type=STRING}]})),
      this.window: org.apache.beam.sdk.transforms.windowing.GlobalWindow@497514c
      window: org.apache.beam.sdk.transforms.windowing.GlobalWindow@497514c

>> Cache HIT

>>> Stale cache
correct value: Map({datasetId=dummy-dset, projectId=dummy-proj, tableId=Client} -> Wrappers.JIterableWrapper({fields=[{mode=REQUIRED, name=client_id, type=STRING}]}), {datasetId=dummy-dset, projectId=dummy-proj, tableId=User} -> Wrappers.JIterableWrapper({fields=[{mode=REQUIRED, name=user_id, type=STRING}]}))
cached  value: Map({datasetId=dummy-dset, projectId=dummy-proj, tableId=User} -> Wrappers.JIterableWrapper({fields=[{mode=REQUIRED, name=user_id, type=STRING}]}))
```

So basically the tests can pass sometimes because the concurrency defeats the cache. When caching does come to play, the test fails. The only solution I can see is to disable caching when using global windows since there's no guarantee of immutability of the side input in that case.

**Closed** 2018-07-09 16:05 UTC
Labels: bug
