### ISSUE TITLE
Can not find implicit coder (scala 2.11)

### ISSUE THREAD

**Issue by JozoVilcek** [spotify/scio#2283] opened 2019-10-03 10:29 UTC
I am running Scio `0.8.0-beta1` and for this scenario:
```scala
object SomeEnum extends Enumeration {
  type SomeEnum = Value
  val Foo: SomeEnum = Value(0)
  val Bar: SomeEnum = Value(1)
}
case class FailingClass(data: Map[(Long, SomeEnum), String])
```
Scio is failing to resolve the `Coder[FailingClass`. However, if I make key of a map more explicit
```
case class Key(a: Long, b: SomeEnum)
case class PassingClass(data: Map[Key, String])
```
the `Coder[PassingClass]` is a success.

Why does coder materialization has a problem with enumeration in Tuple but is fine with using it in case class? Is it a feature or bug?

**Comment by ClaireMcGinty** [comment] 2019-10-03 20:42
thanks! tbh, I'm having a hard time reproducing this; I do see a warning that Kryo is being used for the Enum field specifically, but the case class Coders are correctly materialized by Magnolia. This job works as expected:

```
object SomeEnum extends Enumeration {
  val Foo: Value = Value(0)
  val Bar: Value = Value(1)
}
case class ClassWithTupleField(tupleField: Map[(SomeEnum.Value, Int), String])
case class CaseClassWithEnum(a: SomeEnum.Value, b: Int)
case class ClassWithNestedClassField(nestedField: Map[CaseClassWithEnum, String])

object CoderExampleJob {

  def main(cmdLineArgs: Array[String]): Unit = {
    val (sc, _) = ContextAndArgs(cmdLineArgs)
    sc.parallelize(1 to 10).map { i =>
      ClassWithTupleField(Map((SomeEnum.Foo, i) -> "bar"))
    }.map(print)

    sc.parallelize(1 to 10).map { i =>
      ClassWithNestedClassField(Map(CaseClassWithEnum(SomeEnum.Foo, i) -> "baz"))
    }.map(print)

    sc.close()
  }
}
```
And in the REPL, you can see Coders materialized as:
```
> Coder[SomeEnum.Value]
Fallback(scala.Enumeration$Value)

> Coder[CaseClassWithEnum]
Record(com.spotify.scio.examples.CaseClassWithEnum, (a, Fallback(scala.Enumeration$Value)), (b, Beam(VarIntCoder)))

> Coder[ClassWithTupleField]
Record(com.spotify.scio.examples.ClassWithTupleField, (tupleField, Transform(Transform(Fallback(scala.Enumeration$Value), <function1>), <function1>)))

> Coder[ClassWithNestedClassField]
Record(com.spotify.scio.examples.ClassWithNestedClassField, (nestedField, Transform(Record(com.spotify.scio.examples.CaseClassWithEnum, (a, Fallback(scala.Enumeration$Value)), (b, Beam(VarIntCoder))), <function1>)))
```

can you give more context on what you're seeing?

**Comment by JozoVilcek** [comment] 2019-10-05 17:55
Thanks for the quick feedback. What I see is
```
Cannot find an implicit Coder instance for type:

  >> example.ClassWithTupleField
```
I did a bit more testing and I think the secret sauce is scala version. I am running `2.11` and see a failure there. For `2.12` your example does materialize coder for me.

**Comment by nevillelyh** [comment] 2019-10-10 18:21
Not sure if we can/want to fix this, since 2.11 is really old and behind w.r.t. macros/magnolia support. Can we close this as a `wontfix`?

**Comment by JozoVilcek** [comment] 2019-10-11 10:14
I guess I can live with workaround. But it raises a question for me what does it mean to use a Scio on Scala `2.11`. Unfortunately I can not upgrade Scala version right now.

**Comment by nevillelyh** [comment] 2019-10-28 19:16
Just curious, what's blocking you on 2.11? Feels like something the community should fix.

**Comment by JozoVilcek** [comment] 2019-10-29 08:36
No, it is completely internal. Right now, I am pinned to 2.11 because of old Spark 2.1.x version. One more reason (among many other) to do an upgrade. Thanks

**Comment by nevillelyh** [comment] 2019-10-29 15:32
Derailing a bit here, are you using scio on spark? Curious about you experience with it.

**Comment by JozoVilcek** [comment] 2019-10-29 19:51
Nothing special to note here. I do not need to think in terms of  Scio <-> Spark. If any, we deal with Beam Spark runner <-> Spark issues. Scio is great to wrap Beam SDK into, let's say, more agile and smoother data pipeline transforms. And we use also Flink runner (minor for now) next to Spark.

**Comment by nevillelyh** [comment] 2020-01-15 19:35
Gonna close this. It's increasingly hard to support 2.11 with more and more libraries dropping 2.11 support.

**Closed by nevillelyh** 2020-01-15 19:35 UTC
Labels: bug
